-- MySQL Script generated by MySQL Workbench
-- Wed Jul  3 15:47:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Educature
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  `role_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `Role_role_id` INT NOT NULL,
  `verificationkey` VARCHAR(50),
  `verified` TINYINT NOT NULL,
  `date_created` DATE NOT NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_User_Role_idx` (`Role_role_id` ASC),
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`Role_role_id`)
    REFERENCES `Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDetails` (
  `user_detail_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `facebook_link` VARCHAR(500) NOT NULL,
  `linkedin_link` VARCHAR(500) NOT NULL,
  `github_link` VARCHAR(500) NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`user_detail_id`),
  INDEX `fk_UserDetails_User1_idx` (`User_user_id` ASC),
  CONSTRAINT `fk_UserDetails_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDesignation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDesignation` (
  `designation_id` INT NOT NULL AUTO_INCREMENT,
  `designation_title` VARCHAR(45) NOT NULL,
  `designation_description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`designation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDesignation_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDesignation_has_User` (
  `UserDesignation_designation_id` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`UserDesignation_designation_id`, `User_user_id`),
  INDEX `fk_UserDesignation_has_User_User1_idx` (`User_user_id` ASC),
  INDEX `fk_UserDesignation_has_User_UserDesignation1_idx` (`UserDesignation_designation_id` ASC),
  CONSTRAINT `fk_UserDesignation_has_User_UserDesignation1`
    FOREIGN KEY (`UserDesignation_designation_id`)
    REFERENCES `UserDesignation` (`designation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserDesignation_has_User_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseCategory` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseType` (
  `coursetype_id` INT NOT NULL AUTO_INCREMENT,
  `course type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`coursetype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `course_number` INT NOT NULL,
  `CourseCategory_category_id` INT NOT NULL,
  `course_tag` VARCHAR(45) NOT NULL,
  `CourseType_coursetype_id` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_Courses_CourseCategory1_idx` (`CourseCategory_category_id` ASC),
  INDEX `fk_Courses_CourseType1_idx` (`CourseType_coursetype_id` ASC),
  CONSTRAINT `fk_Courses_CourseCategory1`
    FOREIGN KEY (`CourseCategory_category_id`)
    REFERENCES `CourseCategory` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_CourseType1`
    FOREIGN KEY (`CourseType_coursetype_id`)
    REFERENCES `CourseType` (`coursetype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseDetail` (
  `course_detai_id` INT NOT NULL AUTO_INCREMENT,
  `course_description` VARCHAR(500) NOT NULL,
  `Course_duration` VARCHAR(45) NOT NULL,
  `course_rating` VARCHAR(45) NOT NULL,
  `course_image` VARCHAR(45) NOT NULL,
  `Courses_course_id` INT NOT NULL,
  PRIMARY KEY (`course_detai_id`),
  INDEX `fk_CourseDetail_Courses1_idx` (`Courses_course_id` ASC),
  CONSTRAINT `fk_CourseDetail_Courses1`
    FOREIGN KEY (`Courses_course_id`)
    REFERENCES `Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Video` (
  `video_id` INT NOT NULL AUTO_INCREMENT,
  `video_name` VARCHAR(45) NOT NULL,
  `video_duration` VARCHAR(45) NOT NULL,
  `video_link` VARCHAR(500) NOT NULL,
  `CourseDetail_course_detai_id` INT NOT NULL,
  PRIMARY KEY (`video_id`),
  INDEX `fk_Video_CourseDetail1_idx` (`CourseDetail_course_detai_id` ASC),
  CONSTRAINT `fk_Video_CourseDetail1`
    FOREIGN KEY (`CourseDetail_course_detai_id`)
    REFERENCES `CourseDetail` (`course_detai_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PaymentMethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PaymentMethod` (
  `paymenttype_id` INT NOT NULL AUTO_INCREMENT,
  `payment_method` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paymenttype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_amount` VARCHAR(45) NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  `payment_date` VARCHAR(45) NOT NULL,
  `PaymentMethod_paymenttype_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_Payment_PaymentMethod1_idx` (`PaymentMethod_paymenttype_id` ASC),
  CONSTRAINT `fk_Payment_PaymentMethod1`
    FOREIGN KEY (`PaymentMethod_paymenttype_id`)
    REFERENCES `PaymentMethod` (`paymenttype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User_has_Courses` (
  `User_user_id` INT NOT NULL,
  `Courses_course_id` INT NOT NULL,
  PRIMARY KEY (`User_user_id`, `Courses_course_id`),
  INDEX `fk_User_has_Courses_Courses1_idx` (`Courses_course_id` ASC),
  INDEX `fk_User_has_Courses_User1_idx` (`User_user_id` ASC),
  CONSTRAINT `fk_User_has_Courses_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Courses_Courses1`
    FOREIGN KEY (`Courses_course_id`)
    REFERENCES `Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `total_qty` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  `Payment_payment_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_Order_User1_idx` (`User_user_id` ASC),
  INDEX `fk_Order_Payment1_idx` (`Payment_payment_id` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Payment1`
    FOREIGN KEY (`Payment_payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OrderDeatils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OrderDeatils` (
  `oderdetail_id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATE NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `course_price` DOUBLE NOT NULL,
  `Order_order_id` INT NOT NULL,
  `Courses_course_id` INT NOT NULL,
  PRIMARY KEY (`oderdetail_id`),
  INDEX `fk_OrderDeatils_Order1_idx` (`Order_order_id` ASC),
  INDEX `fk_OrderDeatils_Courses1_idx` (`Courses_course_id` ASC),
  CONSTRAINT `fk_OrderDeatils_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDeatils_Courses1`
    FOREIGN KEY (`Courses_course_id`)
    REFERENCES `Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payment_Details` (
  `paymentdetail_id` INT NOT NULL AUTO_INCREMENT,
  `card_number` INT(16) NOT NULL,
  `card_name` VARCHAR(45) NOT NULL,
  `expirary_date` DATE NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `verification_code` INT NOT NULL,
  `Payment_payment_id` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`paymentdetail_id`),
  INDEX `fk_Payment_Details_Payment1_idx` (`Payment_payment_id` ASC),
  INDEX `fk_Payment_Details_User1_idx` (`User_user_id` ASC),
  CONSTRAINT `fk_Payment_Details_Payment1`
    FOREIGN KEY (`Payment_payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_Details_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `session_id` INT NOT NULL,
  `Active` TINYINT NULL,
  PRIMARY KEY (`cart_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CartItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CartItem` (
  `cartitem_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `course_price` DOUBLE NOT NULL,
  `Cart_cart_id` INT NOT NULL,
  PRIMARY KEY (`cartitem_id`),
  INDEX `fk_CartItem_Cart1_idx` (`Cart_cart_id` ASC),
  CONSTRAINT `fk_CartItem_Cart1`
    FOREIGN KEY (`Cart_cart_id`)
    REFERENCES `Cart` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Courses_has_Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Courses_has_Cart` (
  `Courses_course_id` INT NOT NULL,
  `Cart_cart_id` INT NOT NULL,
  PRIMARY KEY (`Courses_course_id`, `Cart_cart_id`),
  INDEX `fk_Courses_has_Cart_Cart1_idx` (`Cart_cart_id` ASC),
  INDEX `fk_Courses_has_Cart_Courses1_idx` (`Courses_course_id` ASC),
  CONSTRAINT `fk_Courses_has_Cart_Courses1`
    FOREIGN KEY (`Courses_course_id`)
    REFERENCES `Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Cart_Cart1`
    FOREIGN KEY (`Cart_cart_id`)
    REFERENCES `Cart` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
